Repository cpuabuse/cross-cat, pull requests merged in 2020-03, with the labels that each got.

#13 Add: System tests #5
  test/data/dinosaurs.tsv
  test/data/fruits.txt
  test/data/vegetables.txt
  test/expected/index.ts
  test/system/data/system-data.txt
  test/system/system-test.ts
Labels: enhancement

#16 Test: PR
  src/cross-cat.ts
Labels: invalid

#17 Test: PR
  azure-pipelines.yml
Labels: invalid

#18 Test: PR to master
  .gitignore
  .npmignore
  azure-pipelines.yml
  package.json
  script/pipeline/Deploy-GithubRelease.ps1
  script/pipeline/Deploy-NPMLatest.ps1
Labels: invalid

#25 Add: Documentation
  src/cross-cat.ts
Labels: enhancement

#28 Change: Test imports
  azure-pipelines.yml
  package.json
  script/pipeline/Deploy-NPMNext.ps1
  src/cross-cat.ts
  test/system/test.ts
Labels: enhancement

#29 Add: Documentation to source
  src/pipeline/auxiliary/number.ts
  src/pipeline/number-nonblank.ts
  src/pipeline/number.ts
  src/pipeline/show-ends.ts
  src/pipeline/show-nonprinting.ts
  src/pipeline/show-tabs.ts
  src/pipeline/squeeze-blank.ts
Labels: documentation

#34 Add: Documentation to test
  test/expected/index.ts
  test/expected/pipeline.ts
  test/input/pipeline.ts
  test/unit/pipeline/number-nonblank.ts
  test/unit/pipeline/number.ts
  test/unit/pipeline/show-ends.ts
  test/unit/pipeline/show-nonprinting.ts
  test/unit/pipeline/show-tabs.ts
  test/unit/pipeline/squeezeBlank.ts
Labels: documentation

#35 Release: Major
  .gitpod.dockerfile
  .gitpod.yml
  .npmignore
  README.md
  azure-pipelines.yml
  package.json
  script/pipeline/Deploy-NPMNext.ps1
  script/pipeline/Send-Twitter.ps1
  src/pipeline/auxiliary/number.ts
  src/pipeline/number-nonblank.ts
  src/pipeline/number.ts
  src/pipeline/show-ends.ts
  src/pipeline/show-nonprinting.ts
  src/pipeline/show-tabs.ts
  src/pipeline/squeeze-blank.ts
  test/expected/index.ts
  test/expected/pipeline.ts
  test/input/pipeline.ts
  test/unit/pipeline/number-nonblank.ts
  test/unit/pipeline/number.ts
  test/unit/pipeline/show-ends.ts
  test/unit/pipeline/show-nonprinting.ts
  test/unit/pipeline/show-tabs.ts
  test/unit/pipeline/squeezeBlank.ts
  tsconfig.json
Labels: enhancement
